# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.20250225.2
_src_path: gh:level12/copier-py-package
author_email: randy.syring@level12.io
author_name: Randy Syring
hatch_version_tag_sign: true
project_name: pre-commit-hooks
py_module: pre_commit_hooks
python_version: '3.12'
script_name: check-ruff-versions
