[build-system]
requires = [
    'hatchling',
    'hatch-regex-commit',
]
build-backend = 'hatchling.build'


[project]
name = 'pre-commit-hooks'
authors = [
    {name = 'Randy Syring', email = 'randy.syring@level12.io'},
]
requires-python = '>=3.12'
dynamic = ['version']
readme = 'readme.md'
dependencies = [
    "click>=8.1.8",
    "pip-requirements-parser>=32.0.1",
    "pyyaml>=6.0.2",
]


[project.scripts]
'check-ruff-versions' = 'pre_commit_hooks.check_ruff_versions:main'


[dependency-groups]
# Note: keeping Coppy deps grouped separate from app deps should help avoid unnecessary
# conflicts when upgrading to the latest Coppy template.
dev = [
    # From Coppy:
    {include-group = "tests"},
    {include-group = "pre-commit"},
    {include-group = "audit"},
    {include-group = "nox"},
    'click>=8.1.8',
    'hatch>=1.14.0',
    'ruff>=0.9.6',
    # App specific:
    # TODO: fill in app deps here
    "pre-commit-uv>=4.1.4",
]
# Used by nox
tests = [
    # From Coppy:
    'pytest>=8.3.4',
    'pytest-cov>=6.0',

    # App specific:
    # TODO: fill in app deps here
]
# Used by nox
pre-commit = [
    # From Coppy:
    'pre-commit>=4.1.0',
]
# Used by nox
audit = [
    # From Coppy:
    'pip-audit>=2.8.0',
]
# Used by CI
nox = [
    'nox>=2025.2.9',
]
